// <auto-generated />
namespace WebApplication19.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RenameToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201502201754564_Rename Token"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
