// <auto-generated />
namespace Authy2FA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AuthyId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuthyId));
        
        string IMigrationMetadata.Id
        {
            get { return "201502251700440_AuthyId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
